/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Demo: typeof import('./../src/components/demo/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Goback: typeof import('./../src/components/demo/goback.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    Language: typeof import('./../src/components/Language.vue')['default']
    MockApiDemo: typeof import('./../src/components/demo/MockApiDemo.vue')['default']
    MockDemo: typeof import('./../src/components/demo/MockDemo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
